---
- name: install pip prereqs
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ pipPrereqs }}"

- name: install / upgrade pip stuff
  pip:
    name: "{{ item }}"
    state: latest
  with_items: 
    - "{{ pipInstalls }}"

- name: finish prereq installs
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ prereqs }}"


 
