---
- ec2:
    key_name: "{{ ec2key }}"
    instance_type: "{{ ec2type }}"
    image: "{{ ec2ami }}"
    wait: yes
    group: "{{ ec2group }}"
    instance_tags: 
        name: "{{ ec2nametag }}"
    count: "{{ ec2count }}"
    state: "{{ ec2state }}"
    vpc_subnet_id: "{{ ec2subnet }}"
    assign_public_ip: yes
    key_name: "{{ ec2key }}"
    region: "{{ ec2region }}"
    
   
