---
- ec2:
    key_name: "{{ ec2key }}"
    instance_type: "{{ ec2type }}"
    image: "{{ ec2ami }}"
    wait: yes
    group: "{{ ec2group }}"
    count: 1
    vpc_subnet_id: "{{ ec2vpc }}"
    assign_public_ip: yes
    state: "{{ ec2state }}"
    key_name: "{{ ec2key }}"
    reigion: "{{ ec2reigion }}"
    
   
